version: "3"
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-express-server
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production
networks:
  default:
    external: false
