version: "3"
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-express-server
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: production
