apiVersion: v1
kind: Service
metadata:
  name: devops-poc-svc
  namespace: bun-ns
  labels:
    name: devops-poc-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: devops-poc-app
