apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-poc-app
  namespace: bun-ns
  labels:
    name: devops-poc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: devops-poc-app
  template:
    metadata:
      labels:
        name: devops-poc-app
    spec:
      containers:
        - name: devops-poc-app
          image: ffalanges/bun-express-server:v1
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3